language: ruby
cache: 
  - bundler
  - directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
rvm:
- 2.3.3

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: |
  bundle exec jekyll build && bundle exec htmlproofer ./_site \
  --assume-extension \
  --empty-alt-ignore \
  --alt-ignore '/.*/' \
  --file-ignore '/.+/assets/.*/','/.+/lessons/deprecated/.*/' \
  --timeframe '30d' \
  --only-4xx \
  --http-status-ignore 429 \
  --url-ignore http://www.gutenberg.org/ebooks/2600

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

branches:
  only:
    - gh-pages
    - /.*/

# Add slack notifications
notifications:
  slack:
    secure: IQkIaMYJ9fvTiwDguwSFIpnhsUqr4J0dbjwYLsMT4V95k2aPDSP4/D4TmLDElt7ZlI0WxCmNs8kC2GA8OznyNJMpdFwzBfxT/CnHDGcrzv+c+MT5L2CEUzFdDOQpscdmgnlpfaRuE8Vf6TgKBZHiFiBzY5ZI2DpgcixouSLWQW8=
