name: Programming Historian
description: Introductory and intermediate programming lessons for humanists
url: http://programminghistorian.org
baseurl: ""
exclude:
  - deprecated
  - vendor
  - Gemfile
  - Gemfile.lock
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
  -
    scope:
      path: "es"
    values:
      lang: "es"
  -
    scope:
      path: "lessons"
    values:
      lesson: true
  -
    scope:
      path: "lessons/deprecated"
    values:
      lesson: false
  -
    scope:
      path: "es/lecciones"
    values:
      translated-lesson: true

# For local work: bundle exec jekyll serve --watch --baseurl '/proghistdev' or wherever else your local site is located
